# Generated by Django 2.2.7 on 2019-11-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('public_key', models.CharField(max_length=1000)),
                ('encrypt_key', models.CharField(max_length=1000)),
            ],
        ),
    ]
