<html>
  <head>
    <?php
    echo '<title>PHEmail service</title>';
    ?>
    <link rel="shortcut icon" type="image/png" href="/favicon.ico"/>
    <link rel="shortcut icon" type="image/png" href="http://example.com/favicon.png"/>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">

  </head>
  <body>
    <?php
           echo '<p>This content was generated by PHP</p>';
    ?>
    <p>And this content is static HTML</p>
  </body>
</html>
